// Code generated by mockery v2.53.3. DO NOT EDIT.

package services

import (
	courier "lisichkinuriy/delivery/internal/domain/courier"

	mock "github.com/stretchr/testify/mock"

	order "lisichkinuriy/delivery/internal/domain/order"
)

// IOrderDispatcherMock is an autogenerated mock type for the IOrderDispatcher type
type IOrderDispatcherMock struct {
	mock.Mock
}

type IOrderDispatcherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *IOrderDispatcherMock) EXPECT() *IOrderDispatcherMock_Expecter {
	return &IOrderDispatcherMock_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function with given fields: _a0, couriers
func (_m *IOrderDispatcherMock) Dispatch(_a0 *order.Order, couriers []*courier.Courier) (*courier.Courier, error) {
	ret := _m.Called(_a0, couriers)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 *courier.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(*order.Order, []*courier.Courier) (*courier.Courier, error)); ok {
		return rf(_a0, couriers)
	}
	if rf, ok := ret.Get(0).(func(*order.Order, []*courier.Courier) *courier.Courier); ok {
		r0 = rf(_a0, couriers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*courier.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(*order.Order, []*courier.Courier) error); ok {
		r1 = rf(_a0, couriers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrderDispatcherMock_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type IOrderDispatcherMock_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - _a0 *order.Order
//   - couriers []*courier.Courier
func (_e *IOrderDispatcherMock_Expecter) Dispatch(_a0 interface{}, couriers interface{}) *IOrderDispatcherMock_Dispatch_Call {
	return &IOrderDispatcherMock_Dispatch_Call{Call: _e.mock.On("Dispatch", _a0, couriers)}
}

func (_c *IOrderDispatcherMock_Dispatch_Call) Run(run func(_a0 *order.Order, couriers []*courier.Courier)) *IOrderDispatcherMock_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*order.Order), args[1].([]*courier.Courier))
	})
	return _c
}

func (_c *IOrderDispatcherMock_Dispatch_Call) Return(_a0 *courier.Courier, _a1 error) *IOrderDispatcherMock_Dispatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrderDispatcherMock_Dispatch_Call) RunAndReturn(run func(*order.Order, []*courier.Courier) (*courier.Courier, error)) *IOrderDispatcherMock_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewIOrderDispatcherMock creates a new instance of IOrderDispatcherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrderDispatcherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrderDispatcherMock {
	mock := &IOrderDispatcherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
